"""Validate the goal clips generated by the current goal pipeline."""

from pathlib import Path

import cv2
import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
CLIPS_DIR = PROJECT_ROOT / "outputs" / "highlights" / "goals"
OUTPUT_CSV = PROJECT_ROOT / "outputs" / "highlights" / "goal_clip_validation.csv"


def validate_clip(path: Path) -> dict:
    cap = cv2.VideoCapture(str(path))
    opened = cap.isOpened()
    fps = cap.get(cv2.CAP_PROP_FPS) if opened else 0.0
    frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) if opened else 0
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) if opened else 0
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) if opened else 0
    readable_frame, _ = cap.read() if opened else (False, None)
    cap.release()

    valid = bool(opened and readable_frame and fps > 0 and frames > 0)
    return {
        "clip": str(path.relative_to(PROJECT_ROOT)),
        "valid": valid,
        "fps": fps,
        "frames": frames,
        "duration_seconds": round(frames / fps, 3) if fps > 0 else 0.0,
        "width": width,
        "height": height,
    }


def main() -> int:
    clips = sorted(CLIPS_DIR.glob("goal_*.mp4")) if CLIPS_DIR.exists() else []
    results = [validate_clip(path) for path in clips]
    report = pd.DataFrame(
        results,
        columns=[
            "clip", "valid", "fps", "frames", "duration_seconds", "width", "height",
        ],
    )

    OUTPUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    report.to_csv(OUTPUT_CSV, index=False)

    valid_count = int(report["valid"].sum()) if not report.empty else 0
    invalid_count = len(report) - valid_count
    print("GOAL HIGHLIGHT CLIP VALIDATION")
    print(f"Clips found: {len(report)}")
    print(f"Valid: {valid_count}")
    print(f"Invalid: {invalid_count}")
    print(f"Report: {OUTPUT_CSV}")
    if invalid_count:
        print(report.loc[~report["valid"]].to_string(index=False))
        return 1
    if not clips:
        print(f"No goal clips found in {CLIPS_DIR}")
        return 1
    print("All goal clips opened and yielded a readable frame.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
